package com.qsh.springBootDemo.model.auto;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.id
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.student_id
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private Long studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.student_number
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private Long studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.student_password
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private String studentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.real_name
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.isdel
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.create_time
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_management..student.update_time
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.id
     *
     * @return the value of job_management..student.id
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.id
     *
     * @param id the value for job_management..student.id
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.student_id
     *
     * @return the value of job_management..student.student_id
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public Long getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.student_id
     *
     * @param studentId the value for job_management..student.student_id
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setStudentId(Long studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.student_number
     *
     * @return the value of job_management..student.student_number
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public Long getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.student_number
     *
     * @param studentNumber the value for job_management..student.student_number
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setStudentNumber(Long studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.student_password
     *
     * @return the value of job_management..student.student_password
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.student_password
     *
     * @param studentPassword the value for job_management..student.student_password
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.real_name
     *
     * @return the value of job_management..student.real_name
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.real_name
     *
     * @param realName the value for job_management..student.real_name
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.isdel
     *
     * @return the value of job_management..student.isdel
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.isdel
     *
     * @param isdel the value for job_management..student.isdel
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.create_time
     *
     * @return the value of job_management..student.create_time
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.create_time
     *
     * @param createTime the value for job_management..student.create_time
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_management..student.update_time
     *
     * @return the value of job_management..student.update_time
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_management..student.update_time
     *
     * @param updateTime the value for job_management..student.update_time
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}