package com.qsh.springBootDemo.mapper.auto;

import com.qsh.springBootDemo.model.auto.Student;
import com.qsh.springBootDemo.model.auto.StudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    Student selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_management..student
     *
     * @mbg.generated Fri Jan 18 11:01:57 CST 2019
     */
    int updateByPrimaryKey(Student record);
}